### ISSUE TITLE
Java基本数据类型-关于String的intern()方法的使用是不是有点失误？

### ISSUE THREAD

**Issue by atumu** [h2pl/JavaTutorial#10]
[java] view plain copy
String s = new String("1");  
**s.intern();**  
String s2 = "1";  
System.out.println(s == s2);  
  
String s3 = new String("1") + new String("1");  
**s3.intern();**  
String s4 = "11";  
System.out.println(s3 == s4);  
输出结果为：

[java] view plain copy
JDK1.6以及以下：false false  
JDK1.7以及以上：false true

----------------------------------------

是不是该是：
s = s.intern();
s3 = s3.intern();

另外我在JDK1.7和1.8下输出结果均为 false  false，不知是哪里出错了吗？

**Comment by MarioKartMaster** [comment]
我测了一下这个例子，`“1”`编译到类的常量池里所以输出了true，和`intern`毫无关系

**Comment by h2pl** [comment]
欢迎pr哈。感谢指出。

**Comment by h2pl** [comment]
![image](https://user-images.githubusercontent.com/20679558/229131939-01add40b-aa34-4733-95aa-e5b4a31337b9.png)
我在1.8测试的结果是false true
