### ISSUE TITLE
19、Java集合框架梳理.md

### ISSUE THREAD

**Issue by dyhack** [h2pl/JavaTutorial#34]
这一章图里面是否缺少了EnumSet这个集合。我看都有TreeMap

[章节地址](https://github.com/h2pl/Java-Tutorial/blob/master/docs/java/basic/19%E3%80%81Java%E9%9B%86%E5%90%88%E6%A1%86%E6%9E%B6%E6%A2%B3%E7%90%86.md)
![链接地址](https://camo.githubusercontent.com/05238e4a89fbaeef70abb728109fb6ff2ba2c242de37532a76de299dffe16477/68747470733a2f2f696d672d626c6f672e6373646e696d672e636e2f32303139303232323039343430333537392e706e673f782d6f73732d70726f636573733d696d6167652f77617465726d61726b2c747970655f5a6d46755a33706f5a57356e6147567064476b2c736861646f775f31302c746578745f6148523063484d364c7939696247396e4c6d4e7a5a473475626d56304c337036647a45314d7a45304d7a6b774f54413d2c73697a655f31362c636f6c6f725f4646464646462c745f3730)

**Comment by h2pl** [comment]
是的，你很细心哈。这里并没有把所有的集合类纳入

**Comment by dyhack** [comment]
这个回复也太久了哈。。。。等的❀都谢了
