### ISSUE TITLE
图片路径失效了看不了

### ISSUE THREAD

**Issue by antelopeh** [h2pl/JavaTutorial#40]
![111](https://user-images.githubusercontent.com/59186753/132155550-4b74ef02-96d9-4f7d-b720-aa99fba2c42b.jpg)

**Comment by h2pl** [comment]
已修复，感谢提醒

**Comment by antelopeh** [comment]
这是来自QQ邮箱的假期自动回复邮件。 您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
